# Generated by Django 4.1.7 on 2023-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=70)),
                ('image', models.ImageField(upload_to='images')),
                ('number', models.IntegerField()),
                ('description', models.TextField(max_length=7000, null=True)),
            ],
        ),
    ]
