# Generated by Django 4.1.7 on 2023-03-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
