# Generated by Django 4.1.7 on 2023-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
