# Generated by Django 4.1.7 on 2023-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_checkout_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
