# Generated by Django 4.1.7 on 2023-03-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_checkout_cost_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='savat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
