# Generated by Django 4.1.7 on 2023-03-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_checkout_savat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='savat',
        ),
        migrations.AddField(
            model_name='cart',
            name='savat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.checkout'),
        ),
    ]
