# Generated by Django 4.1.7 on 2023-03-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_checkout_savat_cart_savat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='savat',
            new_name='sav',
        ),
    ]
