# Generated by Django 4.1.7 on 2023-03-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_checkout_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
